services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: uv run uvicorn app.main:app --host 0.0.0.0 --port 8080
    restart: no
    volumes:
      - ./:/app # Mount local folder to /app in container
